// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop.Database.Modeler {
    
    
    public partial class ModelerCanvasWidget {
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoDevelop.Database.Modeler.ModelerCanvasWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "MonoDevelop.Database.Modeler.ModelerCanvasWidget";
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
